### ISSUE TITLE
[Asset Ownership Issue] Remove all instances of unauthorized usage of sound file

### ISSUE THREAD

**Issue by Lylythii** [Rebirth-of-the-Night/Rebirth-Of-The-Night#1009]
### Describe the issue
Sound file in question: https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/blob/master/customdisc/assets/customdisc/sounds/signal.ogg

Sound files official source: https://github.com/TerraFirmaCraft-The-Final-Frontier/TFC-TFF/blob/1.12.2/src/main/resources/assets/minecraft/sounds/mob/enderlin/death/1.ogg

Sound file in question is a sound that was produced for usage in a project not associated with RoTN.
RoTN contains an outdated/unfinished version of said sound file that was not officially given to RoTN.

### Expected behavior
Assets to not be taken from other projects without explicit request.

**Comment by EliteMeats** [comment]
Asset has been removed with commit https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/commit/1bc54ad8724e228a5415ce89753c6a0a519a475b

For posterity, permission was indeed granted despite the issue stating otherwise; however for the sake of courtesy it has been removed regardless.
![IMG_2303](https://user-images.githubusercontent.com/70586468/201549611-754d12d2-a286-40a6-8da8-67f41af06be9.jpeg)

**Comment by Lylythii** [comment]
> For posterity, permission was indeed granted despite the issue stating otherwise

If you're going to take it personally rather than simply closing the issue, I could very well point out that this "permission" was, regrettably, *retroactively* given, after you'd implemented the file into RoTN & made use of it, something that should not have been done.
Additionally the file in question was an outdated file I explicitly requested you not to use.
The *initial* permissions granted to you were to "share the file in Discord". Something that occurred *prior* to my joining the RoTN team, purely for demonstrative purposes.

There is no need to be like this.
