### ISSUE TITLE
[BUG] Invasions went back to 30 days instead of 15 days in 3.2.1a update

### ISSUE THREAD

**Issue by Stargen45** [Rebirth-of-the-Night/Rebirth-Of-The-Night#1090]
### Describe the bug

Invasion were fixed in the update 3.2.1 but then in 3.2.1a the hordes config reverted back to being the wrong time like 48000 instead of 24000 which was the 3.2.1.

### To Reproduce

Go into a world and get to night 15 with no invasion

### Expected behavior

The invasion should happen on night 15

### Modpack Version

3.2

### Server or singleplayer

Singleplayer

### Version the world was created on:

3.2

**Comment by Kompreya** [comment]
Can confirm. Invasion frequency was reduced for 3.2.1, as per this commit: https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/commit/10df62887e87feb43839036e12f20087ed76bac5#diff-87a1a7678f3a1b9342edc2f1cf0f8c39b1bd985f06e708639b77b1317e94131e

This was the most recent change, and that configuration was included for 3.2.1 (but not 3.2 as your ticket suggests, just for clarification)

However, 3.2.1a seems to have introduced code regression, as the configuration included is not the same as what was in 3.2.1.

To the developers, it appears a version of hordes.cfg was pulled from stable after Apr 3 (that includes this commit: https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/blob/41becedad02321e0abe1b3ebb357cf94f4ca50d1/config/hordes.cfg) but prior to Apr 8 (that includes this commit: https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/blob/10df62887e87feb43839036e12f20087ed76bac5/config/hordes.cfg) and delivered with 3.2.1a

Unsure how this happened, since the CF release should ideally reflect what was on stable at the time of release.

**Comment by ProvidenceDaemon** [comment]
ty for reporting this, we will have a patch out tonight
