### ISSUE TITLE
[BUG] UGB problems

### ISSUE THREAD

**Issue by Helaxo** [Rebirth-of-the-Night/Rebirth-Of-The-Night#362]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

It's quite simple. When I mine a Soapstone Brick Slab, it drops a Komatite Brick Slab.

Simply mining the slab normally changed the stone type.

Unless my Bronze Pickaxe magically changes the colour, I excpect my Soapstone Slab back.

![image](https://user-images.githubusercontent.com/47443322/83259226-f33a6900-a1b7-11ea-9a86-6cfd8bbc9c48.png)

Version 2.77.4
Server (With FTButils installed)
Version 2.77.1 (I think)
.

**Comment by democat3457** [comment]
https://github.com/Aang23/UndergroundBiomesConstructs/issues/237 opened issue

**Comment by democat3457** [comment]
We got a record of 6 issues referencing this so far!

**Comment by democat3457** [comment]
According to #592, upside down Limestone Stairs have missing item textures.

**Comment by democat3457** [comment]
According to #569, most slabs and stairs have Sturdy mining level, whereas most other blocks have Crude mining level.

**Comment by democat3457** [comment]
<img width="800" alt="Screen Shot 2021-07-25 at 12 55 51 PM" src="https://user-images.githubusercontent.com/32407067/126908595-966a70b7-38ff-442c-8754-2a75e72e06eb.png">
<img width="419" alt="Screen Shot 2021-07-25 at 12 56 07 PM" src="https://user-images.githubusercontent.com/32407067/126908597-236e6c23-a6f7-43e4-80b7-40c8577e61b7.png">

my extent of testing

**Comment by LemADEC** [comment]
Slabs and stairs should be fixed in the next update to UndergroundBiomes

**Comment by KaleThyself** [comment]
✔ = Resolved as of v.3.1.1a.

- [X] Mining a Soapstone Brick Slab drops a Komatite Brick Slab. 
- [X] Mining an Eclogite Brick Slab drops a Black Granite Brick Slab.
- [X] Slab Problems issue 
- [X] Mining a Quartzite Brick Slab drops an Andesite Brick Slab.
- [X] Mining a Marble Brick Slab drops a Rhyolite Brick Slab.
- [X] Mining a Green Schist Brick Slab drops a Basalt Brick Slab.
- [X] #569 
- [X] #592 
- [X] #605 
- [ ] #273 (UNRESOLVED due to missing textures still present in mining particles for all walls.) 
- [X] #737 
- [X] #785

**Comment by democat3457** [comment]
Ok so we'll close this issue and reopen #273 as it seems like everything else here has been solved
