### ISSUE TITLE
[BUG] Quality does not work on mythril armor

### ISSUE THREAD

**Issue by Creatorofpie** [Rebirth-of-the-Night/Rebirth-Of-The-Night#375]
**Describe the bug**
Quality does not work on mythril armor.

**To Reproduce**
1. create mythril armor.
2. go to reforging station and attempt to reforge to a positive quality.
3. the quality does not actually affect you.

**Expected behavior**
The quality should be able to affect your character, I believe this is the only armor where this is an issue.

**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: 2.77.5
 - Server or Singleplayer: Server
 - Version the world was created on: 2.77.4

**Additional context**
I believe the quality did work on 2.77.4.  I guarantee that it works on 2.77.1 and 2.77.2.

**Comment by democat3457** [comment]
Can reproduce on dev.

**Comment by Kompreya** [comment]
Qualities are being removed from armor/weapons/tools next update. Only baubles and magic items will have qualities. We may add qualities back to armor in the future, but implementation will be different.

So, we can mark this "fixed" for 2.78 since you wont be able to get qualities on mythril armor. But we need to consider this bug in our future rework of armor and weapon qualities.

**Comment by democat3457** [comment]
Actually caused by https://discord.com/channels/620840315498004480/664351929505415168/850944888186994708
