### ISSUE TITLE
[BUG] XP Dupe with Xorcite and Biotite

### ISSUE THREAD

**Issue by Oreo12** [Rebirth-of-the-Night/Rebirth-Of-The-Night#424]
**Describe the bug**
**
Right clicking Xorcite ore after mining biotite will give you an infinite amount of experience.
**To Reproduce**
Get to the end, find xorcite, wait for it to be fully matured, mine a single biotite ore, right click xorcite ore to your hearts content.
**Expected behavior**

Not sure lol

**Info (please complete the following information):**
 - Modpack Version: 2.77.5
 - Server or Singleplayer: Server
 - Version the world was created on: 2.77.5

**Comment by KaleThyself** [comment]
The [mod update](https://www.curseforge.com/minecraft/mc-mods/end-reborn/files/3006659) of 0.3.9 End Reborn mod did not fix the Xorcite giving infinite exp issue described above. [3.0 Beta 4]

**Comment by KaleThyself** [comment]
Additionally, when mining end biotite and then heading home to *right click harvest* crops, you get exp per crop harvest for a certain amount of time.

**Comment by CalaMariGold** [comment]
![unknown-96](https://user-images.githubusercontent.com/57605926/115036763-c9576700-9e9b-11eb-9145-a4d998485f8c.png)

**Comment by democat3457** [comment]
tbh end reborn has actually been really un-problematic recently

**Comment by democat3457** [comment]
Can we confirm if this still happens in 3.0b5?

**Comment by KaleThyself** [comment]
This still happens in v.3.0.1.
![image](https://user-images.githubusercontent.com/50285548/163297017-45534cfb-76e5-4043-a518-1502d21e5eaf.png)

**Comment by KaleThyself** [comment]
This bug is still replicable as of version 3.1.1a. 
![image](https://user-images.githubusercontent.com/50285548/176381289-95ead267-9ca4-403b-9d68-48a43b6fbcb6.png)

**Comment by KaleThyself** [comment]
**Update:** The issue does not lie solely with End Reborn surprisingly enough. 

1. When mining a non-vanilla ore with a pickaxe, right clicking to harvest via Quark's feature will give experience as long as you continuously right click to harvest crops. 
2. Since the End Reborn End Flower and Xorcite ore both are considered "crops" with their growth stages, they yield experience infinitely due to this Quark vs modded blocks compatibility bug. 

I'm not sure if another mod is in play, but from what was tested, these two mods are the main culprits of the infinite experience glitch.

**Comment by democat3457** [comment]
This is definitely a very useful report, thanks kale! 🥬

**Comment by kil0byt3** [comment]
Haven’t tested this but it should work: Easily fixable in an afternoon for modpack purposes by turning off Quark’s auto-find-crops feature (quark.cfg line 1644) and finding/adding all crops in RotN to the list instead. Would also be much more versatile later. Of course finding and fixing the underlying bug is better, but in the interim….

**Comment by TheNelston** [comment]
fuckin pain but i guess i got nothing better to do tonight

**Comment by kil0byt3** [comment]
Alternately we could turn off Quark's harvesting feature and add one of the standalone mods that does the same thing. Potentially those mods use a different form of detection that wouldn't cause this bug. And if it still occurs - then use my method posted above

**Comment by TheNelston** [comment]
wait ok kilo you just made me realize something very genius- the glitch with harvesting crops giving you xp is probably caused by this same issue, albeit less abusable because its not infinitely "harvestable"

@democat3457 any way to fix this in quark?

**Comment by democat3457** [comment]
Quark doesn't give xp directly, it must be inside Forge's calls to harvest the block. Also, the Simple Harvest mod works the exact same way in detection and firing (even down to the variable naming, I'm pretty sure the code was copied identically at some point), so using specifically that mod also wouldn't change anything.

**Comment by democat3457** [comment]
However, I could add a blacklist config to prevent certain crops from being right-click harvestable, or I could add a config option to only allow replanting of crops that have seeds (the xorcite cluster does not have seeds)

**Comment by TheNelston** [comment]
please do that

**Comment by democat3457** [comment]
to which, both?

**Comment by TheNelston** [comment]
yeah, both

**Comment by democat3457** [comment]
Crops can no longer be right click harvested if they don’t specify a seed item, and for good measure, xorcite clusters have been added to the blacklist.
