### ISSUE TITLE
[BUG] Hunger Bar Glitch

### ISSUE THREAD

**Issue by JadeBarroth** [Rebirth-of-the-Night/Rebirth-Of-The-Night#440]
**Describe the bug**
Hunger bar is invisible unless food item is in hotbar. When a food item is in the hotbar, a maximum of 5 hunger bars is shown. Player is unable to eat, despite the hunger bar going down. Player still suffers the effects of starvation, including death. 

**To Reproduce**
Go into creative mode, wait for some time, and return to survival mode. 

**Expected behavior**
Player should have a full hunger bar and be able to eat normally upon returning to survival mode. 

**Info (please complete the following information):**
 - Modpack Version: RotN BPG Edition 1.0.3
 - Server or Singleplayer:
 - Version the world was created on: 1.0.2

**Comment by democat3457** [comment]
Hmmmmm... quite curious. However:
1. Most of us devs have been in creative and haven't experienced this bug when switching between gamemodes. (can't repro)
2. Bugs that take an undetermined length of time to reproduce are not bugs worth solving because they happen "randomly" (not necessarily a worthwhile bug)
3. It's on BPG Edition, so it should be reported to Heaveness, not us. (wrong location)
