### ISSUE TITLE
Using copper ingots to craft bakeware yields 3 bakeware items

### ISSUE THREAD

**Issue by KaleThyself** [Rebirth-of-the-Night/Rebirth-Of-The-Night#515]
**Describe the bug**

Attempting to craft harvestcraft:bakewareitem using the simpleores:copper_ingot recipe has a 3x yield. 

**Info (please complete the following information):**

    Modpack Version: 2.77.5
    Server or Singleplayer: Singleplayer via LAN 
    Version the world was created on: 2.77.5

**Screenshots**

![image](https://user-images.githubusercontent.com/50285548/101440543-c89a3d00-38cb-11eb-811e-1b1e97f4b06e.png)

**Comment by KaleThyself** [comment]
In addition, the harvestcraft:cuttingboarditem only has one recipe requiring 1 brick instead of 1 copper ingot alternative like the other cooking ware recipes have.

**Comment by SandwichHorror** [comment]
This is intentional. It's very niche, but since there are no tiers of bakeware, the idea is that copper is a more efficient resource to create simple bakeware, instead of it being 1:1 with clay. You'll rarely need multiple sets of bakeware, but if you do or keep losing them, it's a throwaway use for copper.
