### ISSUE TITLE
[CRASH] Beta ROTN Ferreus Trees(?)

### ISSUE THREAD

**Issue by MochaMochibeep** [Rebirth-of-the-Night/Rebirth-Of-The-Night#564]
**Describe the crash**
Sometimes there's just normal lag/freeze spikes and then it just. Stays frozen. I check the logs after every time it does that, and it seems to be connected with the ferreus veritas trees? (I guess it could just be because I'm using a laptop to play this mod instead of an actual gaming computer.

**To Reproduce**
Steps to reproduce the behavior: Just make a new world and explore it for a while, I think.

**Crash Log**
[17:38:20] [Server thread/INFO]: [com.ferreusveritas.dynamictrees.util.Deprecatron:Complain:17]: Deprecated use of getExactSpecies method. Will be removed in the future.
^Repeatedly.

**Info (please complete the following information):**
 - Modpack Version: 3.0 BETA 2
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 3.0 BETA 2

**Additional context**
EDIT: I've been playing more, and. I guess if you wait long enough it stops? It still lags for around 20 to 40 minutes, I think.

**Comment by democat3457** [comment]
Yikes, those must be some bad specs?
The info line in question refers to how Grove Sprites acquire their tree type via that deprecated method.
It's highly unlikely this will get resolved because Primitive Mobs dev is inactive and lag is pretty common in the beta.
Closing. If it actually crashes with a crash report, feel free to reopen this.
