### ISSUE TITLE
[BUG] xp levels are lost on death while keep inventory is true

### ISSUE THREAD

**Issue by DIVIDERE** [Rebirth-of-the-Night/Rebirth-Of-The-Night#641]
remove this if the behavior is actually intentional.

**Describe the bug**
while keep inventory is set to true the player loses exp on death

**To Reproduce**
turn on keep inventory, earn some exp in survival, die

**Expected behavior**
the player should keep their exp

**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: 3.0 beta 3
 - Server or Singleplayer: single
 - Version the world was created on: 3.0 beta 3

**Additional context**

**Comment by CalaMariGold** [comment]
Confirmed and unintended, likely an issue with CorpseComplex

**Comment by KaleThyself** [comment]
This issue is still replicable as of v.3.1.1a. However, players can easily go into the CorpseComplex mod configs to alter them to their needs. Thus, I believe this issue may be closed. 
https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/blob/5a2a1849928d24c1d50e1f7734f7f1f2258801b7/config/corpsecomplex.cfg#L83-L98
