### ISSUE TITLE
[CRASH] Crash when hovering over exorite when holding shift

### ISSUE THREAD

**Issue by SoulRacer65** [Rebirth-of-the-Night/Rebirth-Of-The-Night#652]
**Describe the crash**
When hovering over Exorite from RotN Blocks when holding shift the game will crash

Vid Showing it happen \/ \/
https://user-images.githubusercontent.com/66193653/108447378-617efa00-7225-11eb-88d9-a90cc38a5331.mp4

**To Reproduce**
Steps to reproduce the behavior: Shift over Exorite in the inventory

**Crash Log**
https://haste.antti.codes/efisaxuxef.mccrash

**Info (please complete the following information):**
 - Modpack Version: 3.0 beta 3
 - Server or Singleplayer: singleplayer
 - Version the world was created on: 3.0 beta 3

**Additional context**
FoamFix, RotN Blocks, and Tool Progression are the causes of the crash

**Comment by Foreck1** [comment]
I can't fix this on my own, since I don't know what would be needed to be changed in the code to stop checking for up and down values of the block (which are causing the crash and are related to Forge changes from previous versions); however, I have access to the code and can edit it, so if anyone knows what needs to be changed, please let me know. 
Exorite crystal:
https://paste.ee/p/gfqie
My suspected lines are of course 82 and 83.

**Comment by Funwayguy** [comment]
I've already addressed this on Discord but I'll leave a note here for future reference.

The issue is not on line 82 or 83 but rather on 117. The block is blindly converting metadata to EnumFacing without enforcing any axis bounds leading to crashes when subtypes queried, in this case by Tool Progression's tooltips. I'd recommend referring to vanilla furnaces for how to implement this properly rather than rely on MCreator's implementation.
