### ISSUE TITLE
[BUG] Witch of Shadows causing major FPS drop

### ISSUE THREAD

**Issue by CalaMariGold** [Rebirth-of-the-Night/Rebirth-Of-The-Night#722]
**Describe the bug**
Witch of Shadows on top of a spider causes major FPS drop

**To Reproduce**  
Spawn a Witch of Shadows riding a spider

**Screenshots**
![image](https://user-images.githubusercontent.com/57605926/112706676-3159f500-8e7c-11eb-96f0-2aef94808d3b.png)

**Info (please complete the following information):**
 - Modpack Version:
   - [ ] 2.77.5
   - [x] 3.0 BETA 4
   - [ ] Other: 
 - Server or Singleplayer:
   - [x] Server
   - [ ] Singleplayer
 - Version the world was created on:
   - [ ] 2.77.5
   - [x] 3.0 BETA 4
   - [ ] Other:

**Comment by KaleThyself** [comment]
I can confirm that this occurs on singleplayer and servers whether the witch of shadows is on a spider or not whenever it aggro's towards anything (player or other mob).

**Comment by CalaMariGold** [comment]
@SandwichHorror this has to do with RotM, can you fix? The FPS drops to like 10

**Comment by democat3457** [comment]
![image](https://user-images.githubusercontent.com/32407067/113755446-edfe5280-96d5-11eb-99e6-a6139a6729e8.png)
if i had to guess, itd be because of this particle cloud
![image](https://user-images.githubusercontent.com/32407067/113755488-fe163200-96d5-11eb-9a11-bd91f1e2ed2a.png)
with rain the effect is even worse, maybe 5 fps
![image](https://user-images.githubusercontent.com/32407067/113755741-4b929f00-96d6-11eb-8612-a64109c90521.png)

**Comment by SandwichHorror** [comment]
Which one is worse, the depth or the smoke particles? Just needs adjustment for density

**Comment by democat3457** [comment]
it feels like it lags more when its all spread out, because then the particles start flickering and it gets really bad
but when its all condensed like in the second picture, it doesnt seem too bad

**Comment by KaleThyself** [comment]
The Witch of Shadows no longer spawns in RotN v.3.1.1a, so this issue may be closed.
