### ISSUE TITLE
[BUG] Stoked Crucible eats up iron and coal dust 

### ISSUE THREAD

**Issue by KaleThyself** [Rebirth-of-the-Night/Rebirth-Of-The-Night#804]
**Describe the bug**
When using a stoked crucible to make steel ingots, putting too much or too little coal dust will consume both the excess ingot and dusts. e.g. 4 ingots and 10 coal dust in the stoked crucible will make 3 ingots of steel, but the last ingot of iron and the 2 coal dusts will be consumed in another cycle of melting. 

**To Reproduce**  
1. Put 4 iron ingots and 10 coal dust into the stoked crucible. 
2. Watch as they turn into 3 steel ingots, but the last cycle of melting consumes the excess materials. 

**Expected behavior**
I expect the last cycle to not occur due to excess materials. 

**Info (please complete the following information):**

 - Modpack Version:
   - [ ] 2.77.5
   - [X] 3.0 BETA 5
   - [ ] Other: 
 - Server or Singleplayer:
   - [ ] Server
   - [X] Singleplayer
 - Version the world was created on:
   - [ ] 2.77.5
   - [X] 3.0 BETA 5
   - [ ] Other:

**Comment by iEatShadows** [comment]
works with regular crucible too.

**Comment by KaleThyself** [comment]
Update: Placing one iron ingot and one coal dust into the stoked/unstoked crucible will cause a cycle to occur and consume the materials without anything in return.

**Comment by democat3457** [comment]
I think the problem lies with the fact that the recipe includes the same ingredient twice, so it gets matched into the same position somehow when checking whether a valid recipe exists. I don't know exactly why stoked is different than unstoked, but I hypothesize (this is probably wrong) that it's because there are technically two recipes that can fit for the stoked crucible over the unstoked crucible, and so removal happens twice? (I doubt this explanation very much because there is an exact check for the heat when getting possible recipes, not something like a "greater than" comparison)

**Comment by Foreck1** [comment]
Following the steps to replicate indev doesn't result in the bug described. Has this been fixed already?

**Comment by KaleThyself** [comment]
> Following the steps to replicate indev doesn't result in the bug described. Has this been fixed already?

Yes, this bug has been fixed in the latest version.
