### ISSUE TITLE
[BUG] Crushed Honeycomb Honey Isn't Usable

### ISSUE THREAD

**Issue by KILLAKAN10** [Rebirth-of-the-Night/Rebirth-Of-The-Night#892]
### Describe the bug

Honey stomped out of the honeycombs is not compatible with fermentation.

Honey From biomes O'plenty hives works, but is nether gated so this isn't exactly a comparable alternative.

### To Reproduce

Crush honeycombs in tub
Realize the liquid that comes out is not ferment-able honey.

### Expected behavior

Honey from rustic should be at-least ferment-able

### Modpack Version

3.1.0

### Server or singleplayer

Singleplayer

### Version the world was created on:

3.1.0

### Additional context

Found #423 when I was trying to see if a similar issue was posted, possibly related.

**Comment by KILLAKAN10** [comment]
A random type of honey is completely useless by oversight and the recipe remains craftable, resulting in a liquid that can't be picked back up, and it just gets wordlessly listed as working as intended?

**Comment by TheNelston** [comment]
1. This is not an oversight, rustic honey will have other uses in the future, and nether honey is the intended method for making mead. Also, we added the not picking up functionality manually, it's intended
2. Whether it's listed or not in the rustic guide is irrelevant, considering rustic brewing is not even used anyways 

I realize now this issue was not raised before on GH, but it has been discussed to death in the Discord, so hopefully this will serve as a reference in the future.

**Comment by KILLAKAN10** [comment]
I see, sorry for complaining, it seemed like an inane thing to do without knowing it was discussed on the discord, I took the tip at face value and didn't check it, rip, still feels weird an something that incomplete is accessible in a release build but ig these things happen. Thanks for explaining it.

**Comment by democat3457** [comment]
the explanation for not being able to pick it up is because it is very very easily duped
